// Real pointer interaction on the portfolio TV; requires the local preview server.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const require=createRequire(path.join(process.env.PROCESS_DESKTOP_RUNTIME,'package.json'));
const {chromium}=require('playwright'),sharp=require('sharp');
const base=process.env.PROCESS_DESKTOP_URL||'http://127.0.0.1:7421';
const out=path.join(root,'prototype/process-desktop/integration');
fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${base}/option-a-desktop/?preview&wall=static#/home`,{waitUntil:'load'});
  const home=page.locator('.win[data-id="home"]');await home.waitFor();
  await home.locator('[data-wact="max"]').click();
  const section=home.locator('#hm-eps'),screen=home.locator('.pe-screen'),img=screen.locator('.pe-img');
  await section.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode());await page.mouse.move(1400,30);
  const before=await screen.screenshot({path:path.join(out,'pointer-before.png')});
  const rect=await screen.boundingBox();
  await page.mouse.move(rect.x+rect.width*.34,rect.y+rect.height*.37,{steps:12});
  await page.waitForFunction(()=>Number(document.querySelector('.pe-screen feDisplacementMap')?.getAttribute('scale'))>20);
  const moving=await screen.screenshot({path:path.join(out,'pointer-distortion.png')});
  const position=await screen.locator('feImage').evaluate(el=>({x:+el.getAttribute('x'),y:+el.getAttribute('y')}));
  await page.mouse.move(rect.x+rect.width*.61,rect.y+rect.height*.49,{steps:8});
  const next=await screen.locator('feImage').evaluate(el=>({x:+el.getAttribute('x'),y:+el.getAttribute('y')}));
  if(Math.abs(next.x-position.x)<40)throw new Error('Displacement does not follow pointer');
  const a=await sharp(before).removeAlpha().raw().toBuffer(),b=await sharp(moving).removeAlpha().raw().toBuffer();
  let changed=0;for(let i=0;i<a.length;i+=3)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>45)changed++;
  if(changed<100)throw new Error('Filter is set but rendered artwork does not visibly distort');
  await page.mouse.move(1400,30);
  await page.waitForFunction(()=>!document.querySelector('.pe-screen .pe-img').style.filter);
  if(await screen.locator('.pe-distort-defs,.crt-pointer-glow').count())throw new Error('Hover resources remain after pointer exits');
  await page.mouse.move(rect.x+rect.width*.4,rect.y+rect.height*.4,{steps:8});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>!document.querySelector('.pe-screen .pe-img').style.filter);
  await page.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.4,{steps:8});
  if(await img.evaluate(el=>Boolean(el.style.filter)))throw new Error('Hover distortion ignores reduce motion');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.mouse.move(rect.x+rect.width*.4,rect.y+rect.height*.4,{steps:8});
  await home.locator('.rm-num[data-i="1"]').click();
  await screen.locator('.pe-img').evaluate(i=>i.decode());
  await page.mouse.move(rect.x+rect.width*.55,rect.y+rect.height*.45,{steps:8});
  if(!(await screen.locator('.pe-img').evaluate(el=>Boolean(el.style.filter))))throw new Error('New episode cannot distort');
  await page.mouse.move(1400,30);
  await page.waitForFunction(()=>!document.querySelector('.pe-screen .pe-img').style.filter);
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  await mobile.goto(`${base}/option-a-desktop/?preview&wall=static#/home`,{waitUntil:'load'});
  await mobile.locator('#hm-eps').scrollIntoViewIfNeeded();
  await mobile.locator('.pe-screen').tap();
  if(await mobile.locator('.pointer-distort,.pe-distort-defs').count())throw new Error('Touch triggered mouse distortion');
  await mobile.close();
  if(errors.length)throw new Error(errors.join('\n'));
  const result={visibleChangedPixels:changed,pointerTracking:true,exitCleanup:true,reducedMotion:true,episodeSwitch:true,touchUnaffected:true,pageErrors:0};
  fs.writeFileSync(path.join(out,'pointer-verification.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
